#!/usr/bin/env node
/**
 * Generate src/embedded-prompts.generated.ts from src/prompts/*.md.
 *
 * Why: the CLI's native binaries (`bun build --compile`) resolve
 * import.meta.url inside bun's virtual filesystem, so runtime readFile of
 * bundled .md assets fails there. Embedding the prompt contents as a plain
 * TS module makes them part of the code — rollup inlines them into the SDK
 * dist and bun embeds them into compiled binaries.
 *
 * The generated file is COMMITTED (a drift test compares it against the .md
 * sources); this script re-runs at the start of every SDK build so local
 * edits to the .md files can never ship stale.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PROMPT_DIR = path.join(ROOT, 'src', 'prompts');
const OUT_FILE = path.join(ROOT, 'src', 'embedded-prompts.generated.ts');

const names = (await readdir(PROMPT_DIR)).filter((name) => name.endsWith('.md')).sort();
if (names.length === 0) {
  throw new Error(`embed-prompts: no .md prompts found in ${PROMPT_DIR}`);
}

const entries = [];
for (const name of names) {
  const content = await readFile(path.join(PROMPT_DIR, name), 'utf8');
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(content)},`);
}

const banner = [
  '// AUTO-GENERATED by scripts/embed-prompts.mjs — DO NOT EDIT.',
  '// Source of truth: src/prompts/*.md. Regenerated on every SDK build;',
  '// a drift test fails if this file and the .md sources disagree.',
  '',
  '/** Bundled prompt assets keyed by file name (fallback when the on-disk',
  ' * prompts are unreachable, e.g. inside bun-compiled native binaries). */',
].join('\n');

await writeFile(OUT_FILE, `${banner}\nexport const EMBEDDED_PROMPTS: Readonly<Record<string, string>> = {\n${entries.join('\n')}\n};\n`);
console.log(`embed-prompts: wrote ${OUT_FILE} (${names.join(', ')})`);
