import { defineConfig } from 'vite-plus';

// AIDEV-NOTE: This root config exists only to hold the `fmt` and `staged`
// blocks: `vp fmt` and `vp check` read Oxfmt settings from `fmt`, and
// `vp staged` (the pre-commit hook) reads its tasks from `staged`. Build and
// test config stays in each package's own vite.config.* and in
// vitest.config.mjs.
//
// The options below are the ones the deleted .prettierrc carried, so replacing
// the formatter did not also change the formatting rules. `ignorePatterns` is
// now the whole answer: Oxfmt reads .gitignore and this list, and nothing else,
// since .prettierignore is gone. That file was load-bearing until it went —
// Oxfmt honours it, and it was the only thing excluding markdown and the
// generated docs trees.
export default defineConfig({
  fmt: {
    printWidth: 120,
    tabWidth: 2,
    useTabs: false,
    semi: true,
    singleQuote: true,
    jsxSingleQuote: true,
    trailingComma: 'all',
    bracketSameLine: false,
    // Oxfmt reorders package.json keys by default. That rewrote 42 manifests
    // here, which is a manifest change rather than a formatting one and is not
    // something Prettier was doing. Keep it off so this stays a formatter swap.
    sortPackageJson: false,
    ignorePatterns: [
      // File types Oxfmt supports but does not own here yet. Markdown and MDX
      // are the next step and their own change: bringing them in rewrites 50
      // files, all table padding and fenced code blocks rather than prose.
      '**/*.md',
      '**/*.mjs',
      '**/*.cjs',
      '**/*.yml',
      '**/*.yaml',
      '**/*.toml',
      '**/*.html',
      '**/*.json5',
      // Consumer-project fixtures with their own toolchains and coding styles.
      // Root-level only, deliberately: `.prettierignore` spelled these as bare
      // `examples` and `demos`, which match a directory of that name at any
      // depth, and that silently took `apps/docs/examples/` — handwritten
      // sample code shown to readers — out of the formatter as well.
      'examples/**',
      'public/**',
      'dist/**',
      '**/dist/**',
      '**/node_modules/**',
      'docs/.vitepress/cache/**',
      'docs/.vitepress/dist/**',
      'vite.config.js',
      'packages/superdoc/src/components/PdfViewer/worker.js',
      'packages/superdoc/src/components/PdfViewer/helpers/pdfjs-worker.js',
      '**/data/**',
      'apps/mcp/src/generated/**',
      // Generated by the docs pipeline: the Document API reference pages, the
      // OpenAPI-shaped JSON under public/, and the fumadocs source index.
      // Carried over from `.prettierignore`, which was the only thing holding
      // them out until it was deleted.
      'apps/docs/generated/**',
      'apps/docs/content/docs/document-api/reference/**',
      'apps/docs/public/reference/**',
      'packages/sdk/langs/browser/src/intent-dispatch.ts',
      'tests/consumer-typecheck/tsconfig.matrix.json',
      'packages/sdk/langs/node/src/embedded-prompts.generated.ts',
    ],
  },
  // Oxlint settings for `vp lint` and the lint step of `vp check`. The ignore
  // list carries over the old eslint.config.mjs scope: generated and vendored
  // sources, plus trees that own their toolchain (apps/docs, examples)
  // or hold test code. Unlike Oxfmt above, which reads .gitignore, `vp lint`
  // only honors this list, so dist output must be repeated here.
  lint: {
    ignorePatterns: [
      // The old root lint script excluded Vue SFCs and Oxlint would lint them;
      // bringing them into scope is a separate decision, not a side effect of
      // replacing ESLint.
      '**/*.vue',
      '**/dist/**',
      '**/dist-types/**',
      '**/pdfjs.js',
      '**/worker.js',
      '**/pdfjs-worker.js',
      '**/*.min.js',
      '**/vendor/**',
      '**/lib/**/*.umd.js',
      'packages/preset-geometry/**',
      '**/src/**/*.d.ts',
      // The old root lint script also excluded these beyond the eslint config:
      // any test/spec suffix and __tests__ directories.
      '**/*.test.*',
      '**/*.spec.*',
      '**/tests/**',
      '**/test/**',
      '**/__tests__/**',
      'apps/docs/**',
      'examples/**',
      '**/examples/**',
      'e2e-tests/**',
    ],
  },
  // Run from the pre-commit hook via `vp staged`. Expensive repo checks that
  // used to run in Lefthook lanes (CLI build, vscode-ext lint, examples
  // validation, react type-check, dts-shadow check) are owned by CI instead:
  // ci-superdoc, ci-vscode-ext, ci-examples, ci-react, and check-dts-shadows
  // workflows.
  staged: {
    '*.{js,jsx,ts,tsx}': 'vp check --fix',
    '*.{css,scss,json,vue}': 'vp fmt --no-error-on-unmatched-pattern',
  },
});
