import path from 'node:path';
import {
  camelCase,
  createOperationTree,
  filterOperationsBySurface,
  loadContract,
  pascalCase,
  resolveRef,
  REPO_ROOT,
  sanitizeOperationId,
  stripBoundParams,
  toNodeType,
  writeGeneratedFile,
} from './shared.mjs';

const NODE_GENERATED_DIR = path.join(REPO_ROOT, 'packages/sdk/langs/node/src/generated');

// ---------------------------------------------------------------------------
// contract.ts — embedded contract JSON
// ---------------------------------------------------------------------------

function generateContractTs(contract) {
  const contractForEmbed = {
    contractVersion: contract.contractVersion,
    ...(contract.$defs ? { $defs: contract.$defs } : {}),
    cli: contract.cli,
    protocol: contract.protocol,
    operations: contract.operations,
  };

  return [
    '/* eslint-disable */',
    '// Auto-generated by packages/sdk/codegen/src/generate-node.mjs',
    '',
    'export interface ContractParamEntry {',
    '  name: string;',
    "  kind: 'doc' | 'flag' | 'jsonFlag';",
    "  type: 'string' | 'number' | 'boolean' | 'json' | 'string[]';",
    '  flag?: string;',
    '  required?: boolean;',
    '  [key: string]: unknown;',
    '}',
    '',
    'export interface ContractOperationEntry {',
    '  operationId: string;',
    '  command: string;',
    '  commandTokens: string[];',
    '  params: ContractParamEntry[];',
    '  constraints?: unknown;',
    '  [key: string]: unknown;',
    '}',
    '',
    'export interface Contract {',
    '  contractVersion: string;',
    '  $defs?: Record<string, unknown>;',
    '  cli: {',
    '    package: string;',
    '    minVersion: string;',
    '  };',
    '  protocol: {',
    '    version: string;',
    '    transport: string;',
    '    features: string[];',
    '    notifications: string[];',
    '  };',
    '  operations: Record<string, ContractOperationEntry>;',
    '}',
    '',
    `export const CONTRACT: Contract = ${JSON.stringify(contractForEmbed, null, 2)};`,
    '',
    `export type OperationEntry = Contract['operations'][keyof Contract['operations']];`,
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Type generation utilities
// ---------------------------------------------------------------------------

function toTsType(typeSpec, indent = '', $defs = undefined) {
  if (!typeSpec) return 'unknown';
  typeSpec = resolveRef(typeSpec, $defs);

  if (Object.prototype.hasOwnProperty.call(typeSpec, 'const')) {
    return JSON.stringify(typeSpec.const);
  }

  if (Array.isArray(typeSpec.oneOf)) {
    const variants = typeSpec.oneOf.map((v) => toTsType(v, indent, $defs));
    return variants.map((v) => (v.includes('\n') ? `(${v})` : v)).join(' | ');
  }

  if (typeSpec.enum && Array.isArray(typeSpec.enum)) {
    return typeSpec.enum.map((v) => JSON.stringify(v)).join(' | ');
  }

  switch (typeSpec.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'array':
      return `Array<${toTsType(typeSpec.items, indent, $defs)}>`;
    case 'object': {
      const required = new Set(typeSpec.required ?? []);
      const props = Object.entries(typeSpec.properties ?? {});
      if (props.length === 0) return 'Record<string, unknown>';
      const lines = ['{'];
      for (const [name, propSpec] of props) {
        const propertyKey = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
          ? name
          : JSON.stringify(name);
        const opt = required.has(name) ? '' : '?';
        lines.push(`${indent}  ${propertyKey}${opt}: ${toTsType(propSpec, `${indent}  `, $defs)};`);
      }
      lines.push(`${indent}}`);
      return lines.join('\n');
    }
    default:
      return 'unknown';
  }
}

// ---------------------------------------------------------------------------
// Param interface generation (from params[] — transport plane)
// ---------------------------------------------------------------------------

function generateParamInterface(operationId, operation, $defs) {
  const name = `Doc${pascalCase(sanitizeOperationId(operationId))}Params`;
  const lines = [`export interface ${name} {`];

  for (const param of operation.params ?? []) {
    const opt = param.required ? '' : '?';
    let paramType;
    if (param.type === 'json' && param.schema) {
      paramType = toTsType(param.schema, '  ', $defs);
    } else {
      paramType = toNodeType(param.type);
    }
    lines.push(`  ${param.name}${opt}: ${paramType};`);
  }

  lines.push('}');
  return { name, source: lines.join('\n') };
}

// ---------------------------------------------------------------------------
// Result type generation (successSchema ?? outputSchema — schema plane)
// ---------------------------------------------------------------------------

function generateResultType(operationId, operation, $defs) {
  const name = `Doc${pascalCase(sanitizeOperationId(operationId))}Result`;
  const schema = operation.successSchema ?? operation.outputSchema;

  if (!schema) {
    throw new Error(`Operation ${operationId} missing both successSchema and outputSchema`);
  }

  const body = toTsType(schema, '', $defs);
  return { name, source: `export type ${name} = ${body};` };
}

// ---------------------------------------------------------------------------
// Response-envelope unwrapping
// ---------------------------------------------------------------------------

// String-typed envelope keys that should use unwrapStringEnvelope instead of unwrapEnvelope.
const STRING_ENVELOPE_KEYS = new Set(['text', 'markdown', 'html']);

// ---------------------------------------------------------------------------
// Client tree rendering
// ---------------------------------------------------------------------------

function renderTreeNode(treeNode, paramTypeMap, resultTypeMap, indent = '    ') {
  const entries = Object.entries(treeNode);
  const rendered = entries.map(([key, value]) => {
    if (value.__operation) {
      const op = value.__operation;
      const typeName = paramTypeMap.get(op.id);
      const resultTypeName = resultTypeMap.get(op.id);
      const hasRequired = (op.params ?? []).some((p) => p.required);
      const paramsArg = hasRequired ? `params: ${typeName}` : `params: ${typeName} = {}`;
      const envelopeKey = op.responseEnvelopeKey ?? null;
      if (envelopeKey) {
        if (STRING_ENVELOPE_KEYS.has(envelopeKey)) {
          return `${indent}${camelCase(key)}: async (${paramsArg}, options?: InvokeOptions): Promise<${resultTypeName}> => unwrapStringEnvelope(await runtime.invoke(CONTRACT.operations[${JSON.stringify(op.id)}], params as unknown as Record<string, unknown>, options), ${JSON.stringify(envelopeKey)}),`;
        }
        return `${indent}${camelCase(key)}: async (${paramsArg}, options?: InvokeOptions): Promise<${resultTypeName}> => unwrapEnvelope<${resultTypeName}>(await runtime.invoke(CONTRACT.operations[${JSON.stringify(op.id)}], params as unknown as Record<string, unknown>, options), ${JSON.stringify(envelopeKey)}),`;
      }
      return `${indent}${camelCase(key)}: (${paramsArg}, options?: InvokeOptions) => runtime.invoke<${resultTypeName}>(CONTRACT.operations[${JSON.stringify(op.id)}], params as unknown as Record<string, unknown>, options),`;
    }

    const nested = renderTreeNode(value, paramTypeMap, resultTypeMap, `${indent}  `);
    return `${indent}${camelCase(key)}: {\n${nested}\n${indent}},`;
  });

  return rendered.join('\n');
}

// ---------------------------------------------------------------------------
// Bound param interface generation (strips doc and sessionId)
// ---------------------------------------------------------------------------

function generateBoundParamInterface(operationId, operation, $defs) {
  const name = `Doc${pascalCase(sanitizeOperationId(operationId))}BoundParams`;
  const boundParams = stripBoundParams(operation.params);
  const lines = [`export interface ${name} {`];

  for (const param of boundParams) {
    const opt = param.required ? '' : '?';
    let paramType;
    if (param.type === 'json' && param.schema) {
      paramType = toTsType(param.schema, '  ', $defs);
    } else {
      paramType = toNodeType(param.type);
    }
    lines.push(`  ${param.name}${opt}: ${paramType};`);
  }

  lines.push('}');
  return { name, source: lines.join('\n') };
}

// ---------------------------------------------------------------------------
// Bound tree rendering (same as raw but uses bound param types)
// ---------------------------------------------------------------------------

function renderBoundTreeNode(treeNode, paramTypeMap, resultTypeMap, indent = '    ') {
  const entries = Object.entries(treeNode);
  const rendered = entries.map(([key, value]) => {
    if (value.__operation) {
      const op = value.__operation;
      const typeName = paramTypeMap.get(op.id);
      const resultTypeName = resultTypeMap.get(op.id);
      const boundParams = stripBoundParams(op.params ?? []);
      const hasRequired = boundParams.some((p) => p.required);
      const paramsArg = hasRequired ? `params: ${typeName}` : `params: ${typeName} = {}`;
      const envelopeKey = op.responseEnvelopeKey ?? null;
      if (envelopeKey) {
        if (STRING_ENVELOPE_KEYS.has(envelopeKey)) {
          return `${indent}${camelCase(key)}: async (${paramsArg}, options?: InvokeOptions): Promise<${resultTypeName}> => unwrapStringEnvelope(await runtime.invoke(CONTRACT.operations[${JSON.stringify(op.id)}], params as unknown as Record<string, unknown>, options), ${JSON.stringify(envelopeKey)}),`;
        }
        return `${indent}${camelCase(key)}: async (${paramsArg}, options?: InvokeOptions): Promise<${resultTypeName}> => unwrapEnvelope<${resultTypeName}>(await runtime.invoke(CONTRACT.operations[${JSON.stringify(op.id)}], params as unknown as Record<string, unknown>, options), ${JSON.stringify(envelopeKey)}),`;
      }
      return `${indent}${camelCase(key)}: (${paramsArg}, options?: InvokeOptions) => runtime.invoke<${resultTypeName}>(CONTRACT.operations[${JSON.stringify(op.id)}], params as unknown as Record<string, unknown>, options),`;
    }

    const nested = renderBoundTreeNode(value, paramTypeMap, resultTypeMap, `${indent}  `);
    return `${indent}${camelCase(key)}: {\n${nested}\n${indent}},`;
  });

  return rendered.join('\n');
}

// ---------------------------------------------------------------------------
// client.ts generation
// ---------------------------------------------------------------------------

function generateClientTs(contract) {
  const $defs = contract.$defs;
  const allOperations = contract.operations;
  const documentOperations = filterOperationsBySurface(allOperations, 'document');

  // Raw param/result types for all operations (used by internal raw API)
  const paramInterfaces = [];
  const resultTypes = [];
  const paramTypeMap = new Map();
  const resultTypeMap = new Map();

  for (const [operationId, operation] of Object.entries(allOperations)) {
    const { name: pName, source: pSource } = generateParamInterface(operationId, operation, $defs);
    paramTypeMap.set(operationId, pName);
    paramInterfaces.push(pSource);

    const { name: rName, source: rSource } = generateResultType(operationId, operation, $defs);
    resultTypeMap.set(operationId, rName);
    resultTypes.push(rSource);
  }

  // Bound param types for document-surface operations only (strip doc/sessionId)
  const boundParamInterfaces = [];
  const boundParamTypeMap = new Map();

  for (const [operationId, operation] of Object.entries(documentOperations)) {
    const { name: bpName, source: bpSource } = generateBoundParamInterface(operationId, operation, $defs);
    boundParamTypeMap.set(operationId, bpName);
    boundParamInterfaces.push(bpSource);
  }

  // Raw operation tree (all operations — internal use only)
  const rawTree = createOperationTree(allOperations);
  const rawTreeSource = renderTreeNode(rawTree, paramTypeMap, resultTypeMap);

  // Bound operation tree (document-surface only — public document handle API)
  const boundTree = createOperationTree(documentOperations);
  const boundTreeSource = renderBoundTreeNode(boundTree, boundParamTypeMap, resultTypeMap);

  return [
    '/* eslint-disable */',
    '// Auto-generated by packages/sdk/codegen/src/generate-node.mjs',
    '',
    "import { CONTRACT } from './contract.js';",
    "import type { RuntimeInvoker, InvokeOptions } from '../runtime/process.js';",
    '',
    '/** Extract a payload value from a CLI response envelope like `{ document, result: {...} }`. */',
    'function unwrapEnvelope<T>(value: unknown, key: string): T {',
    '  if (typeof value === "object" && value !== null) {',
    '    const extracted = (value as Record<string, unknown>)[key];',
    '    if (extracted !== undefined) return extracted as T;',
    '  }',
    '  return value as T;',
    '}',
    '',
    '/** Extract a string value from a CLI response envelope like `{ document, text: "..." }`. */',
    'function unwrapStringEnvelope(value: unknown, key: string): string {',
    '  const extracted = unwrapEnvelope<unknown>(value, key);',
    '  if (typeof extracted === "string") return extracted;',
    '  return extracted as string;',
    '}',
    '',
    '// ---------------------------------------------------------------------------',
    '// Raw param/result types (all operations)',
    '// ---------------------------------------------------------------------------',
    '',
    paramInterfaces.join('\n\n'),
    '',
    resultTypes.join('\n\n'),
    '',
    '// ---------------------------------------------------------------------------',
    '// Bound param types (document-surface only — doc/sessionId stripped)',
    '// ---------------------------------------------------------------------------',
    '',
    boundParamInterfaces.join('\n\n'),
    '',
    '// ---------------------------------------------------------------------------',
    '// Raw API (all operations — internal use only)',
    '// ---------------------------------------------------------------------------',
    '',
    '/** @internal Raw operation tree for SDK internals. Use createBoundDocApi for public document handles. */',
    'export function createDocApi(runtime: RuntimeInvoker) {',
    '  return {',
    rawTreeSource,
    '  };',
    '}',
    '',
    'export type SuperDocDocApi = ReturnType<typeof createDocApi>;',
    '',
    '// ---------------------------------------------------------------------------',
    '// Bound API (document-surface only — public document handle)',
    '// ---------------------------------------------------------------------------',
    '',
    '/** Bound document operation tree. The runtime injects sessionId; callers never pass doc or sessionId. */',
    'export function createBoundDocApi(runtime: RuntimeInvoker) {',
    '  return {',
    boundTreeSource,
    '  };',
    '}',
    '',
    'export type BoundDocApi = ReturnType<typeof createBoundDocApi>;',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

export async function generateNodeSdk(contract) {
  const contractContent = generateContractTs(contract);
  const clientContent = generateClientTs(contract);

  await Promise.all([
    writeGeneratedFile(path.join(NODE_GENERATED_DIR, 'contract.ts'), contractContent),
    writeGeneratedFile(path.join(NODE_GENERATED_DIR, 'client.ts'), clientContent),
  ]);
}

if (import.meta.url.endsWith(process.argv[1]?.replace(/^file:\/\//, '') ?? '')) {
  const contract = await loadContract();
  await generateNodeSdk(contract);
  console.log('Generated Node SDK files.');
}
