export {
  createSuperDocUI,
  shallowEqual,
  type CommentsHandle,
  type CommentsSlice,
  type EqualityFn,
  type SelectorFn,
  type SelectionSlice,
  type Subscribable,
  type SuperDocEditorLike,
  type SuperDocLike,
  type SuperDocUI,
  type SuperDocUIOptions,
  type SuperDocUIState,
} from '@superdoc/super-editor';
