export {
  createSuperDocUI,
  shallowEqual,
  type CommentsHandle,
  type CommentsSlice,
  type EqualityFn,
  type ReviewHandle,
  type ReviewItem,
  type ReviewSlice,
  type SelectorFn,
  type SelectionSlice,
  type Subscribable,
  type SuperDocEditorLike,
  type SuperDocLike,
  type SuperDocUI,
  type SuperDocUIOptions,
  type SuperDocUIState,
  type ViewportGetRectInput,
  type ViewportHandle,
  type ViewportRect,
  type ViewportRectResult,
} from '@superdoc/super-editor';
