/**
 * Extract output helpers for the Node SDK.
 *
 * Pure data transforms over the Document API's `extract()` result. Hand-
 * written, not generated by `pnpm run generate:all`, and stable across
 * SDK versions.
 *
 * The helpers cover three universal needs that every consumer of `extract()`
 * runs into when building retrieval, citation, or review-queue features:
 *
 *   1. `renderBlockText` — turn a block's text + tracked-change spans into
 *      a string with `<ins>`/`<del>` markers (or markdown-style markers).
 *   2. `getTrackedChangeTextParts` / `summarizeTrackedChange` — walk the
 *      spans of the blocks a tracked change covers and return the per-half
 *      text. Necessary for paired replacements where the SDK suppresses
 *      the aggregate excerpt.
 *   3. `getBlocksForTrackedChange` — look up the actual block objects a
 *      tracked change anchors to. Reads `change.blockIds` first, falls
 *      back to scanning spans for older or hand-constructed data.
 *
 * Chunking strategy (chunk size, overlap, table-row vs cell grouping,
 * what to embed) is application-specific and intentionally not part of
 * this module. See the "Content extraction for RAG" recipe in the docs
 * for an opinionated example built on top of these helpers.
 *
 * Usage:
 * ```ts
 * import { createSuperDocClient } from '@superdoc-dev/sdk';
 * import {
 *   renderBlockText,
 *   summarizeTrackedChange,
 *   getBlocksForTrackedChange,
 * } from '@superdoc-dev/sdk/helpers/extract';
 *
 * const client = createSuperDocClient();
 * await client.connect();
 * const doc = await client.open({ doc: './contract.docx' });
 * const extraction = await doc.extract();
 *
 * for (const block of extraction.blocks) {
 *   const html = renderBlockText(block, { trackedChanges: 'html' });
 *   // -> "The <del data-tc-id=\"...\">old</del><ins data-tc-id=\"...\">new</ins> word"
 * }
 *
 * for (const change of extraction.trackedChanges) {
 *   const summary = summarizeTrackedChange(change, extraction);
 *   // -> 'deleted "old", inserted "new"'
 * }
 * ```
 */

// Local structural types — intentionally NOT importing from @superdoc/document-api.
// That's a private workspace package; consumers can't resolve it through their
// own node_modules. The shapes below mirror the Document API's `extract()`
// output. If the contract evolves, we widen the structural types here to stay
// tolerant of forwards-compatible payloads.

/** Tracked-change mark type, matching the Document API's TrackChangeType. */
export type TrackChangeType = 'insert' | 'delete' | 'format';

/** A run of text inside a block, optionally tagged with tracked-change marks. */
export interface ExtractTextSpanLike {
  text: string;
  trackedChanges?: Array<{
    entityId: string;
    type: TrackChangeType;
  }>;
}

/** One block in the extract result. Only the fields these helpers read are required. */
export interface ExtractBlockLike {
  nodeId: string;
  type: string;
  text: string;
  textSpans?: ExtractTextSpanLike[];
}

/** One tracked change in the extract result. */
export interface ExtractTrackedChangeLike {
  entityId: string;
  type: TrackChangeType;
  blockIds?: string[];
  excerpt?: string;
  author?: string;
  date?: string;
  wordRevisionIds?: {
    insert?: string;
    delete?: string;
    format?: string;
  };
}

/** Subset of the extract result used by `getTrackedChangeTextParts`. */
export interface ExtractResultLike {
  blocks: ExtractBlockLike[];
  trackedChanges: ExtractTrackedChangeLike[];
}

/**
 * Output format for `renderBlockText`'s tracked-change markers:
 *
 *   - `'html'` (default): wrap inserted runs in `<ins>` and deleted runs in
 *     `<del>`, including a `data-tc-id` attribute. Span text and attribute
 *     values are HTML-escaped to be safe for direct DOM rendering.
 *   - `'markdown'`: wrap inserted runs as `{+...+}` and deleted runs as
 *     `{-...-}` (CriticMarkup convention). No escaping; markdown sources
 *     expect raw text.
 *   - `'plain'`: drop all markers; return `block.text` unchanged. Useful
 *     when the consumer wants clean text for embedding and reads
 *     `block.textSpans` separately for the structural data.
 */
export type RenderBlockTextFormat = 'html' | 'markdown' | 'plain';

export interface RenderBlockTextOptions {
  trackedChanges?: RenderBlockTextFormat;
}

const HTML_ESCAPE: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, (c) => HTML_ESCAPE[c] ?? c);
}

/**
 * Render a block's text with tracked-change marks visible inline.
 *
 * Returns `block.text` unchanged when the block has no `textSpans` (clean
 * blocks, or older SDK responses). Otherwise concatenates the spans,
 * wrapping each tracked-change run in the requested format's markers.
 *
 * In `'html'` format both span text and the `data-tc-id` attribute are
 * HTML-escaped, so the output is safe to inject into the DOM.
 *
 * Spans tile `block.text` exactly:
 * `block.textSpans.map(s => s.text).join('') === block.text`. The
 * `'plain'` format returns `block.text` directly to make this invariant
 * obvious to consumers.
 *
 * Format-only tracked changes (no inserted or deleted text) are not
 * rendered as markers — the visible text is the same in both pre- and
 * post-edit states. Read `getTrackedChangeTextParts(change, extraction)`
 * if you need to surface a "formatted" change separately.
 */
export function renderBlockText(block: ExtractBlockLike, options: RenderBlockTextOptions = {}): string {
  const format: RenderBlockTextFormat = options.trackedChanges ?? 'html';

  // 'plain' is always raw text — that's the explicit opt-out of escaping.
  if (format === 'plain') return block.text;

  // Clean block (no tracked changes): no markers to inject, but in 'html'
  // mode the text still has to be escaped before it can be safely rendered
  // into the DOM. Skipping this would let untracked content like the
  // literal string "<script>" pass through unescaped.
  if (!block.textSpans || block.textSpans.length === 0) {
    return format === 'html' ? escapeHtml(block.text) : block.text;
  }

  return block.textSpans
    .map((span) => {
      const tc = span.trackedChanges?.find((c) => c.type === 'insert' || c.type === 'delete');
      if (!tc) return format === 'html' ? escapeHtml(span.text) : span.text;

      if (format === 'html') {
        const tag = tc.type === 'insert' ? 'ins' : 'del';
        return `<${tag} data-tc-id="${escapeHtml(tc.entityId)}">${escapeHtml(span.text)}</${tag}>`;
      }
      // markdown
      return tc.type === 'insert' ? `{+${span.text}+}` : `{-${span.text}-}`;
    })
    .join('');
}

/**
 * Per-half text for a tracked change, plus a one-line display summary.
 *
 * `inserted`, `deleted`, and `formatted` each hold the concatenation of
 * span text marked with that type for the given change. For paired
 * replacements both `inserted` and `deleted` populate; for solo edits
 * only one does. `summary` is a display string suitable for citation
 * chunks or review-queue rows.
 */
export interface TrackedChangeTextParts {
  inserted: string;
  deleted: string;
  formatted: string;
  /** Display string like `deleted "X", inserted "Y"`. Empty when no parts. */
  summary: string;
}

/**
 * Walks the spans of the blocks a tracked change covers and returns the
 * per-half text grouped by mark type, plus a display string.
 *
 * For paired replacements (one entity covering both an insert and a
 * delete half) the `inserted` and `deleted` fields each hold the
 * corresponding text. The Document API suppresses the aggregate excerpt
 * for paired entries to avoid concatenating the two halves into one
 * misleading string; this helper is the canonical way to recover them.
 *
 * Falls back to an empty result when none of the change's blocks are
 * present in `extraction.blocks` or when the blocks have no `textSpans`.
 */
export function getTrackedChangeTextParts(
  change: ExtractTrackedChangeLike,
  extraction: ExtractResultLike,
): TrackedChangeTextParts {
  const blocks = getBlocksForTrackedChange(change, extraction.blocks);
  const collected: Record<TrackChangeType, string[]> = {
    insert: [],
    delete: [],
    format: [],
  };

  for (const block of blocks) {
    for (const span of block.textSpans ?? []) {
      for (const tc of span.trackedChanges ?? []) {
        if (tc.entityId !== change.entityId) continue;
        collected[tc.type].push(span.text);
      }
    }
  }

  const inserted = collected.insert.join('');
  const deleted = collected.delete.join('');
  const formatted = collected.format.join('');

  const parts: string[] = [];
  if (deleted) parts.push(`deleted "${deleted}"`);
  if (inserted) parts.push(`inserted "${inserted}"`);
  if (formatted) parts.push(`reformatted "${formatted}"`);

  return { inserted, deleted, formatted, summary: parts.join(', ') };
}

/**
 * Convenience wrapper around `getTrackedChangeTextParts` that returns
 * just the display string. Suitable for embedding into a citation chunk
 * or showing as a one-line summary in a review-queue UI.
 *
 * Prefers `change.excerpt` when present (the SDK's authoritative text
 * for non-paired entries) and falls back to the derived summary for
 * paired replacements.
 */
export function summarizeTrackedChange(change: ExtractTrackedChangeLike, extraction: ExtractResultLike): string {
  if (change.excerpt) return change.excerpt;
  return getTrackedChangeTextParts(change, extraction).summary;
}

/**
 * Returns the blocks whose `textSpans` carry a given tracked change.
 *
 * Reads `change.blockIds` first (the canonical anchor field on Document
 * API responses). Falls back to scanning every block's spans for the
 * entity id when `blockIds` is empty or undefined — useful for older SDK
 * responses or hand-constructed extract data where the field may not be
 * set.
 *
 * Blocks are returned in the order they appear in the input array, which
 * matches document order on Document API responses.
 */
export function getBlocksForTrackedChange(
  change: ExtractTrackedChangeLike,
  blocks: ExtractBlockLike[],
): ExtractBlockLike[] {
  if (change.blockIds && change.blockIds.length > 0) {
    const wanted = new Set(change.blockIds);
    return blocks.filter((b) => wanted.has(b.nodeId));
  }
  return blocks.filter((b) =>
    (b.textSpans ?? []).some((span) => (span.trackedChanges ?? []).some((tc) => tc.entityId === change.entityId)),
  );
}
