/**
 * Consumer typecheck: main "superdoc" entry point.
 *
 * Exercises every public runtime export and type import.
 * If this file compiles, consumers can use these APIs.
 */

// Runtime imports
import {
  Editor,
  PresentationEditor,
  SuperDoc,
  superEditorHelpers,
  createTheme,
  buildTheme,
  getRichTextExtensions,
  getStarterExtensions,
  Extensions,
  createZip,
  DOCX,
  PDF,
  HTML,
  getMarksFromSelection,
  getActiveFormatting,
  getAllowedImageDimensions,
  isNodeType,
  isMarkType,
  defineNode,
  defineMark,
  TrackChangesBasePluginKey,
  CommentsPluginKey,
  DocxZipper,
  SuperToolbar,
} from 'superdoc';

// Type imports
import type {
  EditorState,
  Transaction,
  Schema,
  EditorView,
  EditorCommands,
  ChainableCommandObject,
  ChainedCommand,
  CommandProps,
  Command,
  CanObject,
  CoreCommandMap,
  ExtensionCommandMap,
  OpenOptions,
  DocxFileEntry,
  BinaryData,
  SaveOptions,
  ExportOptions,
  PresentationEditorOptions,
  LayoutEngineOptions,
  PageSize,
  PageMargins,
  VirtualizationOptions,
  TrackedChangesMode,
  TrackedChangesOverrides,
  LayoutMode,
  PresenceOptions,
  RemoteUserInfo,
  RemoteCursorState,
  Layout,
  LayoutPage,
  LayoutFragment,
  RangeRect,
  BoundingRect,
  LayoutError,
  LayoutMetrics,
  PositionHit,
  FlowBlock,
  Measure,
  SectionMetadata,
  PaintSnapshot,
  LayoutUpdatePayload,
  UnsupportedContentItem,
  SelectionHandle,
  SelectionCommandContext,
  ResolveRangeOutput,
  Comment,
  CommentElement,
  LayoutState,
  ImageSelectedEvent,
  ImageDeselectedEvent,
  TelemetryEvent,
  RemoteCursorsRenderPayload,
  FlowMode,
  ProofingProvider,
  ProofingCapabilities,
  ProofingCheckRequest,
  ProofingCheckResult,
  ProofingSegment,
  ProofingSegmentMetadata,
  ProofingIssue,
  ProofingIssueKind,
  ProofingConfig,
  ProofingStatus,
  ProofingError,
  PageStyles,
} from 'superdoc';
