// Generates src/bundled-families.ts: the Word family names a document can curate via
// createSuperDocFonts({ include / exclude }), mirrored from @superdoc/font-system's runtime curation
// set (every logical family the resolver substitutes to a bundled face, including category fallbacks
// like Verdana) - NOT the asset manifest's narrower metric-clone `replaces`.
//
// Skips when the font-system source is absent (a rare standalone install), leaving the committed file;
// in the monorepo a real import error fails loudly. Committed so npm consumers get the list without
// re-generating. Re-run via `pnpm --filter @superdoc-dev/fonts generate` when the curation set changes.
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../src/bundled-families.ts');
const fontSystemSource = resolve(here, '../../../shared/font-system/src/font-offerings.ts');

if (!existsSync(fontSystemSource)) {
  console.log(
    '[@superdoc-dev/fonts] font-system source not present (standalone install); kept committed src/bundled-families.ts',
  );
  process.exit(0);
}

// eslint-disable-next-line import-x/no-relative-packages -- build-only script (not shipped); @superdoc-dev/fonts stays a dependency-free runtime package and font-system exposes no /src export, so reading its source relatively here is intentional
const { getBundledFamilyNames } = await import('../../../shared/font-system/src/font-offerings');
const names = getBundledFamilyNames();
if (names.length === 0) {
  console.error('[@superdoc-dev/fonts] font-system returned no curatable families');
  process.exit(1);
}

const content = `/**
 * GENERATED by scripts/generate-bundled-families.ts - do not edit by hand.
 *
 * The Word family names a document can curate via createSuperDocFonts({ include / exclude }), mirrored
 * from @superdoc/font-system's runtime curation set (every logical family the resolver substitutes to a
 * bundled face, including category fallbacks like Verdana). A name outside this set is a typo or an
 * unbundled font, so createSuperDocFonts rejects it instead of silently dropping the intended fonts.
 */
export const BUNDLED_FAMILY_NAMES = Object.freeze([
${names.map((name) => `  ${JSON.stringify(name)},`).join('\n')}
] as const);

/**
 * Union of the Word family names the bundled pack can curate, for autocomplete on
 * createSuperDocFonts({ include / exclude }). Those options also accept any string (case- and
 * quote-insensitive, validated at runtime), so a list built from dynamic config still type-checks.
 */
export type BundledFontFamilyName = (typeof BUNDLED_FAMILY_NAMES)[number];
`;

let output = content;
try {
  const prettier = await import('prettier');
  const config = (await prettier.resolveConfig(outFile)) ?? {};
  output = await prettier.format(content, { ...config, filepath: outFile });
} catch {
  // Prettier optional; the unformatted output is still valid TypeScript.
}

writeFileSync(outFile, output);
console.log(`[@superdoc-dev/fonts] wrote ${names.length} curatable family names -> src/bundled-families.ts`);
