// Generates src/bundled-families.ts: the Word family names a document can curate via
// createSuperDocFonts({ include / exclude }), mirrored from @superdoc/font-system's runtime curation
// set (every logical family the resolver substitutes to a bundled face, including category fallbacks
// like Verdana) - NOT the asset manifest's narrower metric-clone `replaces`.
//
// Inside the monorepo a missing font-system source is a failure: generating nothing would leave the
// committed list stale and let `check:families` compare it against itself. Outside it, absence is
// expected and the committed file stands. See `font-system-source.mjs`.
// Committed so npm consumers get the list without re-generating. Re-run via
// `pnpm --filter @superdoc/fonts generate` when the curation set changes.
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { FONT_SYSTEM_OFFERINGS, resolveFontSystemPath } from './font-system-source.mjs';
import { formatGenerated } from './lib/format-generated.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../src/bundled-families.ts');

const source = resolveFontSystemPath(FONT_SYSTEM_OFFERINGS, 'source');
if (!source.ok) {
  if (source.skip) {
    console.log(`${source.message}; kept committed src/bundled-families.ts`);
    process.exit(0);
  }
  console.error(source.message);
  process.exit(1);
}

const { getBundledFamilyNames } = await import(pathToFileURL(FONT_SYSTEM_OFFERINGS).href);
const names = getBundledFamilyNames();
if (names.length === 0) {
  console.error('[@superdoc/fonts] font-system returned no curatable families');
  process.exit(1);
}

const content = `/**
 * GENERATED by scripts/generate-bundled-families.ts - do not edit by hand.
 *
 * The Word family names a document can curate via createSuperDocFonts({ include / exclude }), mirrored
 * from @superdoc/font-system's runtime curation set (every logical family the resolver substitutes to a
 * bundled face, including category fallbacks like Verdana). A name outside this set is a typo or an
 * unbundled font, so createSuperDocFonts rejects it instead of silently dropping the intended fonts.
 */
export const BUNDLED_FAMILY_NAMES = Object.freeze([
${names.map((name) => `  ${JSON.stringify(name)},`).join('\n')}
] as const);

/**
 * Union of the Word family names the bundled pack can curate, for autocomplete on
 * createSuperDocFonts({ include / exclude }). Those options also accept any string (case- and
 * quote-insensitive, validated at runtime), so a list built from dynamic config still type-checks.
 */
export type BundledFontFamilyName = (typeof BUNDLED_FAMILY_NAMES)[number];
`;

writeFileSync(outFile, formatGenerated(content, outFile));
console.log(`[@superdoc/fonts] wrote ${names.length} curatable family names -> src/bundled-families.ts`);
