name: Open an issue
description: Report a bug, request a feature, or ask a question
labels:
  - "stage: triage"
body:
  - type: textarea
    id: description
    attributes:
      label: What's on your mind?
      description: Describe the bug, feature, or question.
      placeholder: |
        Tips for bug reports:
        - What happened vs what you expected
        - Steps to reproduce (if known)
        - Attach a sample file or screenshot if possible
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SuperDoc version (if relevant)
      placeholder: e.g. 1.7.0

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, sample files, error messages, browser/OS info, etc.
