import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  testIgnore: '**/legacy/**',
  fullyParallel: true,
  workers: process.env.CI ? '50%' : '75%',
  timeout: 60_000,
  retries: process.env.CI ? 1 : 0,
  reporter: 'list',

  use: {
    viewport: { width: 1600, height: 1200 },
    trace: process.env.TRACE === '1' ? 'on' : 'off',
    screenshot: process.env.SCREENSHOTS === '1' ? 'on' : 'off',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],

  // CI: shard across runners with --shard=1/3, --shard=2/3, --shard=3/3
  webServer: {
    // Sync the gitignored @superdoc-dev/fonts package assets before serving. The package-import font
    // spec resolves faces to `packages/fonts/assets/*.woff2` (via the harness source alias), and
    // those are generated by the fonts package's prepare/build - which behavior CI skips
    // (`--ignore-scripts`, and root build only builds superdoc). Syncing here keeps a clean local or
    // CI checkout honest. `sync` is a standalone copy from shared/font-system/assets (idempotent).
    command: 'pnpm --filter @superdoc-dev/fonts run sync && pnpm exec vite --config harness/vite.config.ts harness/',
    port: 9990,
    reuseExistingServer: !process.env.CI,
  },
});
