/**
 * Clean DOCX agent runtime.
 *
 * This barrel exposes the four product-stable agent tool entry points
 * (inspect, apply, verify, operation) plus the IR types and the
 * contract-derived operation catalog. Consumers should depend on this
 * barrel — never reach into the benchmark `workflow-poc` profile from
 * product code.
 */
export {
  AGENT_TOOL_DEFINITIONS,
  AGENT_TOOL_NAMES,
  isAgentToolName,
  listAgentTools,
  type AgentToolDefinition,
  type AgentToolName,
  type AgentProviderTool,
} from './catalog.js';
export {
  agentInspect,
  agentApply,
  agentVerify,
  agentOperation,
  type AgentApplyArgs,
  type AgentInspectArgs,
  type AgentOperationArgs,
  type AgentReceipt,
  type AgentVerifyArgs,
  type SelectedTarget,
  type VerificationResult,
} from './runtime.js';
export {
  validatePlan,
  isApplyStep,
  isInspectStep,
  isSelectStep,
  isVerifyStep,
  type AgentApplyStep,
  type AgentChangeMode,
  type AgentEntityKind,
  type AgentInspectStep,
  type AgentOrdinalKind,
  type AgentPlan,
  type AgentPlanStep,
  type AgentSelectStep,
  type AgentSelector,
  type AgentVerificationCheck,
  type AgentVerifyStep,
  type IrValidationError,
  type IrValidationResult,
} from './ir.js';
export {
  OPERATION_CATALOG,
  getOperationCatalogEntry,
  getOperationCatalogSummary,
  listMutatingOperations,
  listOperationsByDomain,
  listOperationsMissingStructuralVerification,
  type ExposureStatus,
  type OperationCatalogEntry,
  type OperationDomain,
  type OperationMode,
  type TargetShape,
} from './operation-catalog.js';
export {
  AmbiguousSelectorError,
  buildDocumentSnapshot,
  resolveSnapshotSelector,
  type DocumentSnapshot,
  type SnapshotBlock,
  type SnapshotComment,
  type SnapshotDiagnostic,
  type SnapshotDomain,
  type SnapshotImage,
  type SnapshotList,
  type SnapshotSection,
  type SnapshotTable,
  type SnapshotTrackedChange,
} from './doc-snapshot.js';
export {
  superdocPerformAction,
  isActionName,
  ACTION_NAMES_LIST,
  type AcceptTrackedChangesArgs,
  type AddCommentsArgs,
  type AddHyperlinkArgs,
  type AddListItemsArgs,
  type ApplyLetterSpacingArgs,
  type ApplyStyleArgs,
  type AppendListArgs,
  type AttachNumberingArgs,
  type ConvertListArgs,
  type FormatParagraphArgs,
  type FormatTextArgs,
  type InsertPageBreakArgs,
  type MoveTextArgs,
  type RedoChangesArgs,
  type ReplyToCommentArgs,
  type ResolveCommentsArgs,
  type SetFontFamilyArgs,
  type SetParagraphSpacingArgs,
  type SplitListArgs,
  type UndoChangesArgs,
  type CommentParagraphsArgs,
  type CreateTableArgs,
  type DeleteTableColumnArgs,
  type DeleteTableRowArgs,
  type DeleteTextArgs,
  type FillPlaceholdersArgs,
  type InsertHeadingArgs,
  type StyleTableArgs,
  type MoveTableArgs,
  type DeleteTableArgs,
  type InsertListItemsArgs,
  type InsertParagraphsArgs,
  type InsertTableColumnArgs,
  type InsertTableRowArgs,
  type InsertTocArgs,
  type MoveRangeArgs,
  type NormalizeBodyFontSizeArgs,
  type ActionArgs,
  type ActionName,
  type ActionPlacement,
  type RejectTrackedChangesArgs,
  type ReplaceTextArgs,
  type RewriteBlockArgs,
  type SplitTableArgs,
} from './actions.js';
